spring:
  application:
    name: payment-service
  datasource:
    url: "jdbc:sqlite:payment.db"
    driver-class-name: org.sqlite.JDBC
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.proxiadsee.interview.task.payment.config.SQLiteDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
jakarta:
  persistence:
    jdbc:
      url: "jdbc:sqlite:payment.db"
      driver: org.sqlite.JDBC
